---
title: "Project Recipients"
output: flexdashboard::flex_dashboard
self_contained: false
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, warning=FALSE}
source("libraries.R")
source("project_recipients.R")
source("project_indicators.R")
source("preprocess_GIS.R")
```

## Mapping {.tabset}
### Civil Works

```{r}
plotted_GIS
```

## Recipient Tables {.tabset}
### Mechanical Ventilator
```{r}
recipients_equipment%>%
  filter(project_description %in% c("Mechanical Ventilator")
         )%>%
  select(facility_name,
         region,
         project_description,
         quantity)%>%
  arrange(project_description)%>%
  mutate(facility_name = facility_name%>%
           str_replace_all(".*General Hospital and Satellite Trauma Center",
                           "Las Piñas General Hospital and Satellite Trauma Center"))%>%
  DT::datatable(
    colnames = c("Item" = "project_description",
                 "Region" = "region",
                 "Facility Name" = "facility_name",
                 "Quantity" = "quantity"),
    height = 850,
    filter = "none",
    options = list(
      scrollY = "450px",
      columnDefs = list(
        list(
          className = 'dt-center',
          targets = 2:4
          )
        ),
      # searching = F,
      pageLength = 20
      )
    )

```

### Portable X-ray
```{r}
recipients_equipment%>%
  filter(project_description %in% c("Portable X-ray")
         )%>%
  select(facility_name,
         region,
         project_description,
         quantity)%>%
  arrange(project_description)%>%
  mutate(facility_name = facility_name%>%
           str_replace_all(".*General Hospital and Satellite Trauma Center",
                           "Las Piñas General Hospital and Satellite Trauma Center"))%>%
  DT::datatable(
    colnames = c("Item" = "project_description",
                 "Region" = "region",
                 "Facility Name" = "facility_name",
                 "Quantity" = "quantity"),
    height = 850,
    filter = "none",
    options = list(
      scrollY = "450px",
      columnDefs = list(
        list(
          className = 'dt-center',
          targets = 2:4
          )
        ),
      # searching = F,
      pageLength = 20
      )
    )

```

### Infusion Pump
```{r}
recipients_equipment%>%
  filter(project_description %in% c("Infusion Pump")
         )%>%
  select(facility_name,
         region,
         project_description,
         quantity)%>%
  arrange(project_description)%>%
  mutate(facility_name = facility_name%>%
           str_replace_all(".*General Hospital and Satellite Trauma Center",
                           "Las Piñas General Hospital and Satellite Trauma Center"))%>%
  DT::datatable(
    colnames = c("Item" = "project_description",
                 "Region" = "region",
                 "Facility Name" = "facility_name",
                 "Quantity" = "quantity"),
    height = 850,
    filter = "none",
    options = list(
      scrollY = "450px",
      columnDefs = list(
        list(
          className = 'dt-center',
          targets = 2:4
          )
        ),
      # searching = F,
      pageLength = 20
      )
    )

```

### Ambulance
```{r}
recipients_equipment%>%
  filter(grepl("Ambulance", .$project_description, ignore.case = T)
         )%>%
  select(facility_name,
         region,
         project_description,
         quantity)%>%
  arrange(project_description)%>%
  mutate(facility_name = facility_name%>%
           str_replace_all(".*General Hospital and Satellite Trauma Center",
                           "Las Piñas General Hospital and Satellite Trauma Center"))%>%
  DT::datatable(
    colnames = c("Item" = "project_description",
                 "Region" = "region",
                 "Facility Name" = "facility_name",
                 "Quantity" = "quantity"),
    height = 850,
    filter = "none",
    options = list(
      scrollY = "450px",
      columnDefs = list(
        list(
          className = 'dt-center',
          targets = 2:4
          )
        ),
      # searching = F,
      pageLength = 20
      )
    )

```

### Consumables
```{r}
recipients_equipment%>%
  filter(project_description %in% c("PPE and Mask")
         )%>%
  select(facility_name,
         region,
         project_description,
         quantity)%>%
  arrange(project_description)%>%
  mutate(facility_name = facility_name%>%
           str_replace_all(".*General Hospital and Satellite Trauma Center",
                           "Las Piñas General Hospital and Satellite Trauma Center"))%>%
  DT::datatable(
    colnames = c("Item" = "project_description",
                 "Region" = "region",
                 "Facility Name" = "facility_name",
                 "Quantity" = "quantity"),
    height = 850,
    filter = "none",
    options = list(
      scrollY = "450px",
      columnDefs = list(
        list(
          className = 'dt-center',
          targets = 2:4
          )
        ),
      # searching = F,
      pageLength = 20
      )
    )

```

### RT PCR
```{r}
rt_pcr%>%
  DT::datatable(
    colnames = c(
      "Province" = "province",
      "Region" = "region",
      "Facility Name" = "facility_name"
    ),
    height = 850,
    options = list(
      scrollY = "450px",
      columnDefs = list(
        list(
          className = 'dt-center',
          targets = 1:2
          )
        ),
      # searching = F,
      pageLength = 20
      )
    )

```

### Civil Works
```{r}
merged_GIS%>%
  select(Facility.Name,
         project_description,
         status)%>%
  arrange(project_description,
          Facility.Name)%>%
  mutate(Facility.Name = Facility.Name%>%
           str_replace_all(".*General Hospital and Satellite Trauma Center",
                           "Las Piñas General Hospital and Satellite Trauma Center"))%>%
  DT::datatable(
    colnames = c("Item" = "project_description",
                 "Status" = "status",
                 "Facility Name" = "Facility.Name"),
    height = 850,
    filter = "none",
    options = list(
      scrollY = "450px",
      columnDefs = list(
        list(
          className = 'dt-center',
          targets = 2:3
          )
        ),
      # searching = F,
      pageLength = 20
      )
    )

```
