# Equipment ----

recipients_equipment <- tibble(
  data.frame(
     stringsAsFactors = FALSE,
                 region = c("Region 7",
                            "Region 1","Region 1","Region 2","NCR","Region 4A",
                            "Region 5","Region 5","Region 6","Region 7",
                            "Region 7","Region 8","Region 10","Region 11","Region 13",
                            "Region 3","NCR","NCR","Region 6","Region 7",
                            "Region 9","Region 10","Region 11","Region 3",
                            "CAR","NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","Region 1","Region 1","Region 1","Region 2",
                            "Region 2","Region 2","Region 3","Region 3",
                            "Region 3","Region 4A","Region 4B","Region 5",
                            "Region 5","Region 6","Region 6","Region 7",
                            "Region 7","Region 8","Region 10","Region 10",
                            "Region 11","Region 11","Region 12","Region 13",
                            "Region 13","Region 10","CAR","CAR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","CAR","Region 1","Region 1",
                            "Region 1","Region 2","Region 2","Region 2","Region 2",
                            "Region 3","Region 3","Region 3","Region 3",
                            "Region 3","Region 4A","Region 4B","Region 4B",
                            "Region 5","Region 5","Region 5","Region 6",
                            "Region 6","Region 6","Region 6","Region 7","Region 7",
                            "Region 7","Region 7","Region 7","Region 7",
                            "Region 8","Region 8","Region 9","Region 9",
                            "Region 9","Region 9","Region 9","Region 9","Region 10",
                            "Region 10","Region 11","Region 11","Region 12",
                            "Region 13","Region 13","Region 12","Region 10",
                            "Region 9","CAR","CAR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","CAR","Region 1","Region 1","Region 1",
                            "Region 2","Region 2","Region 2","Region 3",
                            "Region 3","Region 3","Region 4A","Region 5","Region 5",
                            "Region 6","Region 6","Region 7","Region 7",
                            "Region 8","Region 9","Region 10","Region 10",
                            "Region 11","Region 11","Region 12","Region 13",
                            "Region 13","Region 10","CAR","CAR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","Region 1","Region 1","Region 1","Region 2",
                            "Region 2","Region 2","Region 2","Region 3",
                            "Region 3","Region 3","Region 3","Region 3",
                            "Region 4A","Region 4B","Region 4B","Region 5",
                            "Region 5","Region 5","Region 6","Region 6","Region 6",
                            "Region 6","Region 7","Region 7","Region 7",
                            "Region 7","Region 7","Region 7","Region 8",
                            "Region 8","Region 9","Region 9","Region 9","Region 9",
                            "Region 9","Region 9","Region 10","Region 10",
                            "Region 11","Region 11","Region 12","Region 13",
                            "Region 13","Region 12","Region 10","Region 9",
                            "CAR","CAR","CAR","CAR","CAR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","CAR","Region 1","Region 1",
                            "Region 1","Region 2","Region 2","Region 2","Region 2",
                            "Region 3","Region 3","Region 3","Region 3",
                            "Region 3","Region 4A","Region 4B","Region 4B",
                            "Region 5","Region 5","Region 5","Region 6",
                            "Region 6","Region 6","Region 6","Region 7","Region 7",
                            "Region 7","Region 7","Region 7","Region 7",
                            "Region 8","Region 8","Region 9","Region 9",
                            "Region 9","Region 9","Region 9","Region 9","Region 10",
                            "Region 10","Region 11","Region 11","Region 12",
                            "Region 13","Region 13","Region 12","Region 10",
                            "Region 9","CAR","NCR","NCR","CAR","NCR",
                            "NCR","NCR","NCR","NCR","NCR","NCR","NCR","NCR",
                            "NCR","NCR","NCR","Region 1","Region 1",
                            "Region 1","Region 2","Region 2","Region 2","Region 3",
                            "Region 3","Region 3","Region 4A","Region 4A",
                            "Region 4B","Region 5","Region 6","Region 6",
                            "Region 7","Region 7","Region 8","Region 9",
                            "Region 9","Region 10","Region 11","Region 11",
                            "Region 12","Region 13","Region 13","Region 10","BARMM",
                            "BARMM","CAR","Region 1","Region 1","Region 2",
                            "Region 3","Region 3","Region 3","Region 3"),
          facility_name = c("Cebu Station (BOQ)",
                            "Dagupan City","La Union","Ilagan, Isabela",
                            "Las Piñas - Trc","Tagaytay City","Malinao, Albay",
                            "San Fernando, Camarines Sur","Pototan, Iloilo",
                            "Argao, Cebu","Cebu City","Dulag, Leyte",
                            "Malaybalay, Bukidnon","Davao City","Caraga",
                            "Clark, Pampanga Station","Manila Station (Port Area)",
                            "Pasay Station (Boq Central Office)","Kalibo, Aklan Station",
                            "Cebu Station","Zamboanga Station",
                            "Cagayan De Oro","Davao Station","Tarlac Provincial Hospital",
                            "Baguio General Hospital and Medical Center",
                            "Amang Rodriguez Memorial Medical Center",
                            "Dr. Jose N. Rodriguez Memorial Hospital",
                            "East Avenue Medical Center","Jose R. Reyes Memorial Medical Center",
                            "Las Piñas General Hospital and Satellite Trauma Center",
                            "Lung Center of the Philippines",
                            "National Children's Hospital","Philippine Children's Medical Center",
                            "Philippine Heart Center",
                            "Philippine Orthopedic Center","Quirino Memorial Medical Center",
                            "Rizal Medical Center","San Lazaro Hospital",
                            "Tondo Medical Center","Valenzuela Medical Center",
                            "Ilocos Training and Regional Medical Center",
                            "Mariano Marcos Memorial Hospital and Medical Center",
                            "Region 1 Medical Center","Cagayan Valley Medical Center",
                            "Region 2 Trauma and Medical Center",
                            "Southern Isabela Medical Center",
                            "Bataan General Hospital and Medical Center",
                            "Dr. Paulino J. Garcia Memorial Research and Medical Center",
                            "Jose B. Lingad Memorial Regional Hospital","Batangas Medical Center",
                            "Ospital Ng Palawan","Bicol Medical Center",
                            "Bicol Regional Training and Teaching Hospital",
                            "Corazon Locsin Montelibano Memorial Regional Hospital",
                            "Western Visayas Sanitarium",
                            "Gov. Celestino Gallares Memorial Hospital","Vicente Sotto Memorial Medical Center",
                            "Eastern Visayas Regional Medical Center",
                            "Mayor Hilarion A. Ramiro, Sr., Medical Center",
                            "Northern Mindanao Medical Center","Davao Regional Medical Center",
                            "Southern Philippines Medical Center",
                            "Cotabato Regional and Medical Center",
                            "Adela Serra Ty Memorial Medical Center","Caraga Regional Hospital",
                            "Amai Pakpak Medical Center",
                            "Luis Hora Memorial Regional Hospital",
                            "Baguio General Hospital and Medical Center","Amang Rodriguez Memorial Medical Center",
                            "Dr. Jose Fabella Memorial Hospital",
                            "Dr. Jose N. Rodriguez Memorial Hospital","East Avenue Medical Center",
                            "Jose R. Reyes Memorial Medical Center",
                            "Las Piñas General Hospital and Satellite Trauma Center",
                            "Lung Center of the Philippines",
                            "National Center for Mental Health","National Children's Hospital",
                            "National Kidney and Transplant Institute",
                            "Philippine Children's Medical Center",
                            "Philippine Heart Center","Philippine Orthopedic Center",
                            "Quirino Memorial Medical Center",
                            "Research Institute for Tropical Medicine","Rizal Medical Center",
                            "San Lazaro Hospital","Tondo Medical Center",
                            "Valenzuela Medical Center","San Lorenzo Ruiz Women's Hospital",
                            "Conner District Hospital",
                            "Ilocos Training and Regional Medical Center",
                            "Mariano Marcos Memorial Hospital and Medical Center","Region 1 Medical Center",
                            "Batanes General Hospital","Cagayan Valley Medical Center",
                            "Region 2 Trauma and Medical Center",
                            "Southern Isabela Medical Center",
                            "Bataan General Hospital and Medical Center",
                            "Dr. Paulino J. Garcia Memorial Research and Medical Center",
                            "Jose B. Lingad Memorial Regional Hospital","Talavera General Hospital",
                            "Mariveles Mental Hospital","Batangas Medical Center",
                            "Culion Sanitarium and General Hospital",
                            "Ospital Ng Palawan","Bicol Medical Center",
                            "Bicol Region General Hospital and Geriatric Medical Center",
                            "Bicol Regional Training and Teaching Hospital",
                            "Corazon Locsin Montelibano Memorial Regional Hospital",
                            "Don Jose S. Monfort Medical Center Extension Hospital",
                            "Western Visayas Medical Center",
                            "Western Visayas Sanitarium",
                            "Don Emilio Del Valle Memorial Hospital","Eversley Childs Sanitarium",
                            "St. Anthony Mother and Child Hospital",
                            "Gov. Celestino Gallares Memorial Hospital","Talisay District Hospital",
                            "Vicente Sotto Memorial Medical Center",
                            "Eastern Visayas Regional Medical Center",
                            "Schistosomiasis Control and Research Hospital","Basilan General Hospital",
                            "Dr. Jose Rizal Memorial Hospital",
                            "Labuan Public Hospital","Margosatubig Regional Hospital",
                            "Mindanao Central Sanitarium","Zamboanga City Medical Center",
                            "Mayor Hilarion A. Ramiro, Sr., Medical Center",
                            "Northern Mindanao Medical Center",
                            "Davao Regional Medical Center","Southern Philippines Medical Center",
                            "Cotabato Regional and Medical Center",
                            "Adela Serra Ty Memorial Medical Center",
                            "Caraga Regional Hospital","Cotabato Sanitarium",
                            "Amai Pakpak Medical Center","Sulu Sanitarium",
                            "Far North Luzon General Hospital and Training Center",
                            "Luis Hora Memorial Regional Hospital",
                            "Amang Rodriguez Memorial Medical Center","Dr. Jose Fabella Memorial Hospital",
                            "Dr. Jose N. Rodriguez Memorial Hospital",
                            "East Avenue Medical Center",
                            "Jose R. Reyes Memorial Medical Center",
                            "Las Piñas General Hospital and Satellite Trauma Center","Lung Center of the Philippines",
                            "National Center for Mental Health",
                            "National Children's Hospital",
                            "National Kidney and Transplant Institute","Philippine Children's Medical Center",
                            "Philippine Heart Center","Philippine Orthopedic Center",
                            "Quirino Memorial Medical Center",
                            "Research Institute for Tropical Medicine","Rizal Medical Center",
                            "San Lazaro Hospital","Tondo Medical Center",
                            "Valenzuela Medical Center",
                            "Baguio General Hospital and Medical Center",
                            "Ilocos Training and Regional Medical Center",
                            "Mariano Marcos Memorial Hospital and Medical Center","Region 1 Medical Center",
                            "Cagayan Valley Medical Center",
                            "Region 2 Trauma and Medical Center","Southern Isabela Medical Center",
                            "Bataan General Hospital and Medical Center",
                            "Dr. Paulino J. Garcia Memorial Research and Medical Center",
                            "Jose B. Lingad Memorial Regional Hospital",
                            "Batangas Medical Center","Bicol Medical Center",
                            "Bicol Regional Training and Teaching Hospital",
                            "Corazon Locsin Montelibano Memorial Regional Hospital",
                            "Western Visayas Medical Center",
                            "Gov. Celestino Gallares Memorial Hospital",
                            "Vicente Sotto Memorial Medical Center","Eastern Visayas Regional Medical Center",
                            "Zamboanga City Medical Center",
                            "Mayor Hilarion A. Ramiro, Sr., Medical Center",
                            "Northern Mindanao Medical Center","Davao Regional Medical Center",
                            "Southern Philippines Medical Center",
                            "Cotabato Regional and Medical Center",
                            "Adela Serra Ty Memorial Medical Center","Caraga Regional Hospital",
                            "Amai Pakpak Medical Center","Luis Hora Memorial Regional Hospital",
                            "Baguio General Hospital and Medical Center",
                            "Amang Rodriguez Memorial Medical Center",
                            "Dr. Jose Fabella Memorial Hospital",
                            "Dr. Jose N. Rodriguez Memorial Hospital","East Avenue Medical Center",
                            "Jose R. Reyes Memorial Medical Center",
                            "Las Piñas General Hospital and Satellite Trauma Center",
                            "Lung Center of the Philippines",
                            "National Center for Mental Health","National Children's Hospital",
                            "National Kidney and Transplant Institute",
                            "Philippine Children's Medical Center","Philippine Heart Center",
                            "Philippine Orthopedic Center",
                            "Quirino Memorial Medical Center","Rizal Medical Center",
                            "San Lazaro Hospital","Tondo Medical Center",
                            "Valenzuela Medical Center","Ilocos Training and Regional Medical Center",
                            "Mariano Marcos Memorial Hospital and Medical Center","Region 1 Medical Center",
                            "Batanes General Hospital","Cagayan Valley Medical Center",
                            "Region 2 Trauma and Medical Center",
                            "Southern Isabela Medical Center",
                            "Bataan General Hospital and Medical Center",
                            "Dr. Paulino J. Garcia Memorial Research and Medical Center",
                            "Jose B. Lingad Memorial Regional Hospital","Talavera General Hospital",
                            "Mariveles Mental Hospital","Batangas Medical Center",
                            "Culion Sanitarium and General Hospital","Ospital Ng Palawan",
                            "Bicol Medical Center",
                            "Bicol Region General Hospital and Geriatric Medical Center",
                            "Bicol Regional Training and Teaching Hospital",
                            "Corazon Locsin Montelibano Memorial Regional Hospital",
                            "Don Jose S. Monfort Medical Center Extension Hospital",
                            "Western Visayas Medical Center","Western Visayas Sanitarium",
                            "Don Emilio Del Valle Memorial Hospital",
                            "Eversley Childs Sanitarium",
                            "St. Anthony Mother and Child Hospital","Gov. Celestino Gallares Memorial Hospital",
                            "Talisay District Hospital",
                            "Vicente Sotto Memorial Medical Center",
                            "Eastern Visayas Regional Medical Center",
                            "Schistosomiasis Control and Research Hospital","Basilan General Hospital",
                            "Dr. Jose Rizal Memorial Hospital","Labuan Public Hospital",
                            "Margosatubig Regional Hospital",
                            "Mindanao Central Sanitarium","Zamboanga City Medical Center",
                            "Mayor Hilarion A. Ramiro, Sr., Medical Center",
                            "Northern Mindanao Medical Center","Davao Regional Medical Center",
                            "Southern Philippines Medical Center",
                            "Cotabato Regional and Medical Center",
                            "Adela Serra Ty Memorial Medical Center","Caraga Regional Hospital",
                            "Cotabato Sanitarium","Amai Pakpak Medical Center",
                            "Sulu Sanitarium","Conner District Hospital",
                            "Far North Luzon General Hospital and Training Center",
                            "Luis Hora Memorial Regional Hospital",
                            "Baguio General Hospital and Medical Center",
                            "Conner District Hospital","Amang Rodriguez Memorial Medical Center",
                            "Dr. Jose Fabella Memorial Hospital",
                            "Dr. Jose N. Rodriguez Memorial Hospital",
                            "East Avenue Medical Center","Jose R. Reyes Memorial Medical Center",
                            "Las Piñas General Hospital and Satellite Trauma Center",
                            "Lung Center of the Philippines",
                            "National Center for Mental Health","National Children's Hospital",
                            "National Kidney and Transplant Institute",
                            "Philippine Children's Medical Center",
                            "Philippine Heart Center","Philippine Orthopedic Center",
                            "Quirino Memorial Medical Center",
                            "Research Institute for Tropical Medicine","Rizal Medical Center",
                            "San Lazaro Hospital","Tondo Medical Center",
                            "Valenzuela Medical Center","San Lorenzo Ruiz Women's Hospital",
                            "Far North Luzon General Hospital and Training Center",
                            "Ilocos Training and Regional Medical Center",
                            "Mariano Marcos Memorial Hospital and Medical Center",
                            "Region 1 Medical Center","Batanes General Hospital",
                            "Cagayan Valley Medical Center",
                            "Region 2 Trauma and Medical Center","Southern Isabela Medical Center",
                            "Bataan General Hospital and Medical Center",
                            "Dr. Paulino J. Garcia Memorial Research and Medical Center","Jose B. Lingad Memorial Regional Hospital",
                            "Talavera General Hospital","Mariveles Mental Hospital",
                            "Batangas Medical Center",
                            "Culion Sanitarium and General Hospital","Ospital Ng Palawan",
                            "Bicol Medical Center",
                            "Bicol Region General Hospital and Geriatric Medical Center",
                            "Bicol Regional Training and Teaching Hospital",
                            "Corazon Locsin Montelibano Memorial Regional Hospital",
                            "Don Jose S. Monfort Medical Center Extension Hospital",
                            "Western Visayas Medical Center","Western Visayas Sanitarium",
                            "Don Emilio Del Valle Memorial Hospital",
                            "Eversley Childs Sanitarium","St. Anthony Mother and Child Hospital",
                            "Gov. Celestino Gallares Memorial Hospital",
                            "Talisay District Hospital",
                            "Vicente Sotto Memorial Medical Center","Eastern Visayas Regional Medical Center",
                            "Schistosomiasis Control and Research Hospital",
                            "Basilan General Hospital",
                            "Dr. Jose Rizal Memorial Hospital","Labuan Public Hospital",
                            "Margosatubig Regional Hospital","Mindanao Central Sanitarium",
                            "Zamboanga City Medical Center",
                            "Mayor Hilarion A. Ramiro, Sr., Medical Center",
                            "Northern Mindanao Medical Center","Davao Regional Medical Center",
                            "Southern Philippines Medical Center",
                            "Cotabato Regional and Medical Center",
                            "Adela Serra Ty Memorial Medical Center","Caraga Regional Hospital",
                            "Cotabato Sanitarium","Amai Pakpak Medical Center",
                            "Sulu Sanitarium","Luis Hora Memorial Regional Hospital",
                            "Afp Medical Center","AFP Medical Center",
                            "Baguio General Hospital and Medical Center",
                            "Amang Rodriguez Memorial Medical Center",
                            "Dr. Jose Fabella Memorial Hospital","Dr. Jose N. Rodriguez Memorial Hospital",
                            "East Avenue Medical Center",
                            "Jose R. Reyes Memorial Medical Center","Lung Center of the Philippines",
                            "National Kidney and Transplant Institute",
                            "Philippine Children's Medical Center",
                            "Quirino Memorial Medical Center",
                            "Research Institute for Tropical Medicine","Rizal Medical Center","San Lazaro Hospital",
                            "Ilocos Training and Regional Medical Center",
                            "Mariano Marcos Memorial Hospital and Medical Center",
                            "Region 1 Medical Center",
                            "Cagayan Valley Medical Center","Region 2 Trauma and Medical Center",
                            "Southern Isabela Medical Center",
                            "Bataan General Hospital and Medical Center",
                            "Dr. Paulino J. Garcia Memorial Research and Medical Center",
                            "Jose B. Lingad Memorial Regional Hospital","Batangas Medical Center",
                            "Southern Tagalog Regional Hospital",
                            "Culion Sanitarium and General Hospital",
                            "Bicol Regional Training and Teaching Hospital",
                            "Corazon Locsin Montelibano Memorial Regional Hospital",
                            "Western Visayas Medical Center",
                            "Gov. Celestino Gallares Memorial Hospital","Vicente Sotto Memorial Medical Center",
                            "Eastern Visayas Regional Medical Center",
                            "Dr. Jose Rizal Memorial Hospital",
                            "Zamboanga City Medical Center","Northern Mindanao Medical Center",
                            "Davao Regional Medical Center",
                            "Southern Philippines Medical Center","Cotabato Regional and Medical Center",
                            "Adela Serra Ty Memorial Medical Center",
                            "Caraga Regional Hospital","Amai Pakpak Medical Center",
                            "Maguindanao Provincial Hospital",
                            "Datu Halun Sakilan Memorial Hospital","Benguet General Hospital",
                            "Gabriela Silang General Hospital",
                            "Pangasinan Provincial Hospital","Batanes General Hospital",
                            "Aurora Memorial Hospital","Bulacan Medical Center",
                            "Tarlac Provincial Hospital",
                            "President Ramon Magsaysay Memorial Hospital"),
          facility_type = c("BUREAU OF QUARANTINE STATION","TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS","TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS","TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS","TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS",
                            "TREATMENT REHABILITATION CENTERS","TREATMENT REHABILITATION CENTERS",
                            "BUREAU OF QUARANTINE STATION",
                            "BUREAU OF QUARANTINE STATION","BUREAU OF QUARANTINE STATION",
                            "BUREAU OF QUARANTINE STATION","BUREAU OF QUARANTINE STATION",
                            "BUREAU OF QUARANTINE STATION",
                            "BUREAU OF QUARANTINE STATION","BUREAU OF QUARANTINE STATION",
                            "LGU PROVINCIAL HOSPITALS","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","AFP","AFP","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL","DOH HOSPITAL",
                            "DOH HOSPITAL","DOH HOSPITAL",
                            "LGU PROVINCIAL HOSPITALS","LGU PROVINCIAL HOSPITALS",
                            "LGU PROVINCIAL HOSPITALS","LGU PROVINCIAL HOSPITALS",
                            "LGU PROVINCIAL HOSPITALS","LGU PROVINCIAL HOSPITALS",
                            "LGU PROVINCIAL HOSPITALS","LGU PROVINCIAL HOSPITALS",
                            "LGU PROVINCIAL HOSPITALS","LGU PROVINCIAL HOSPITALS"),
                  level = c(NA,NA,NA,NA,NA,
                            NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,
                            NA,NA,NA,NA,NA,NA,3L,3L,3L,3L,3L,2L,3L,
                            3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,3L,3L,1L,3L,3L,3L,1L,3L,3L,
                            3L,2L,3L,3L,3L,3L,2L,2L,2L,2L,3L,3L,3L,
                            3L,3L,3L,2L,3L,3L,3L,3L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,1L,1L,3L,3L,3L,1L,3L,3L,3L,
                            3L,3L,3L,1L,3L,3L,1L,1L,3L,1L,3L,3L,1L,
                            3L,1L,1L,1L,1L,3L,1L,3L,3L,1L,1L,1L,2L,
                            1L,1L,3L,2L,3L,3L,3L,3L,2L,2L,1L,2L,1L,
                            1L,2L,3L,3L,3L,3L,3L,2L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,
                            3L,2L,3L,3L,3L,3L,2L,2L,2L,2L,3L,3L,3L,
                            3L,3L,3L,2L,3L,3L,3L,3L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,3L,3L,1L,3L,3L,3L,3L,3L,3L,
                            1L,3L,3L,1L,1L,3L,1L,3L,3L,1L,3L,1L,1L,
                            1L,1L,3L,1L,3L,3L,1L,1L,1L,2L,1L,1L,3L,
                            2L,3L,3L,3L,3L,2L,2L,1L,2L,1L,1L,1L,2L,
                            3L,1L,3L,3L,3L,3L,3L,2L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,3L,3L,3L,3L,1L,1L,3L,3L,3L,
                            1L,3L,3L,3L,3L,3L,3L,1L,3L,3L,1L,1L,3L,
                            1L,3L,3L,1L,3L,1L,1L,1L,1L,3L,1L,3L,3L,
                            1L,1L,1L,2L,1L,1L,3L,2L,3L,3L,3L,3L,2L,
                            2L,1L,2L,1L,2L,NA,NA,3L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,3L,
                            3L,3L,3L,3L,NA,1L,3L,3L,3L,3L,3L,3L,1L,
                            3L,3L,3L,3L,3L,2L,2L,2L,NA,NA,NA,NA,NA,
                            NA,NA,NA,NA,NA),
    project_description = c("Sea Ambulance",
                            "Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Ambulance Type 1","Ambulance Type 1",
                            "Ambulance Type 1","Mechanical Ventilator",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Ambulance Type 2","Ambulance Type 2",
                            "Ambulance Type 2","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Infusion Pump","Infusion Pump",
                            "Infusion Pump","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Mechanical Ventilator","Mechanical Ventilator",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray",
                            "Portable X-ray","Portable X-ray","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask","PPE and Mask",
                            "PPE and Mask","PPE and Mask","PPE and Mask",
                            "Ambulance Type 2","Mechanical Ventilator",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine","RT-PCR machine","RT-PCR machine",
                            "RT-PCR machine"),
               quantity = c(1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,2L,1L,
                            1L,1L,1L,1L,1L,4L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,16L,4L,16L,11L,11L,5L,16L,8L,5L,11L,
                            11L,11L,5L,15L,2L,11L,11L,11L,3L,11L,11L,
                            11L,11L,11L,11L,11L,11L,11L,16L,11L,10L,
                            10L,10L,10L,10L,15L,10L,11L,10L,12L,11L,13L,
                            10L,10L,10L,10L,10L,2L,2L,1L,2L,3L,2L,
                            1L,2L,2L,1L,2L,2L,2L,2L,4L,2L,2L,2L,1L,
                            2L,2L,2L,2L,2L,2L,2L,2L,2L,2L,1L,1L,2L,
                            1L,1L,3L,1L,2L,2L,2L,3L,1L,1L,2L,1L,3L,
                            2L,3L,2L,1L,1L,1L,1L,1L,1L,3L,1L,2L,2L,
                            3L,2L,1L,1L,1L,1L,1L,1L,2L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,5L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,1L,
                            1L,1L),
                 status = c("for_delivery",
                            "for_procurement","for_procurement","for_procurement",
                            "for_procurement","for_procurement",
                            "for_procurement","for_procurement","for_procurement",
                            "for_procurement","for_procurement","for_procurement",
                            "for_procurement","for_procurement","for_procurement",
                            "for_procurement","for_procurement",
                            "for_procurement","for_procurement","for_procurement",
                            "for_procurement","for_procurement","for_procurement",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","delivered","delivered","delivered",
                            "delivered","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","delivered",
                            "delivered","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery","for_delivery",
                            "for_delivery","for_delivery")
  )
)

# RT-PCR ----
rt_pcr <- tibble(
  region = c(
    "NCR",
    "NCR",
    "NCR",
    "NCR",
    "NCR",
    "NCR",
    "NCR",
    "NCR",
    "NCR",
    "CAR",
    "CAR",
    "1",
    "1",
    "1",
    "1",
    "2",
    "2",
    "3",
    "3",
    "3",
    "3",
    "IV-B",
    "6",
    "6",
    "7",
    "7",
    "7",
    "8",
    "10",
    "11",
    "11",
    "12",
    "13",
    "13",
    "IV-B",
    "NCR",
    "NCR",
    "CAR",
    "3",
    "10",
    "NCR",
    "NCR",
    "2",
    "IV-A",
    "5",
    "9",
    "NCR",
    "1",
    "13",
    "13"
  ),
  province = c(
    "Metro Manila",
    "Metro Manila",
    "Metro Manila",
    "Metro Manila",
    "Metro Manila",
    "Metro Manila",
    "Metro Manila",
    "Metro Manila",
    "Metro Manila",
    "Benguet",
    "Mountain Province",
    "La Union",
    "Ilocos Norte",
    "Pangasinan",
    "Pangasinan",
    "Cagayan",
    "Isabela",
    "Bataan",
    "Pampanga",
    "Zambales",
    "Tarlac",
    "Oriental Mindoro",
    "Negros Occidental",
    "Aklan",
    "Cebu",
    "Bohol",
    "Cebu",
    "Leyte",
    "Misamis Oriental",
    "Davao Del Norte",
    "Davao del Sur",
    "Cotabato",
    "Surigao Del Sur",
    "Agusan Del Sur",
    "Palawan",
    "Metro Manila",
    "Metro Manila",
    "Benguet",
    "Nueva Ecija",
    "Lanao Del Sur",
    "Metro Manila",
    "Metro Manila",
    "Nueva Vizcaya",
    "Cavite",
    "Albay",
    "Zamboanga Del Norte",
    "Metro Manila",
    "Ilocos Sur",
    "Surigao Del Norte",
    "Surigao Del Norte"
  ),
  facility_name = c(
    "Amang Rodriguez Memorial Medical Center",
    "Dr. Jose N. Rodriguez Memorial Hospital",
    "Lung Center of The Philippines",
    "National Kidney and Transplant Institute",
    "Philippine Children's Medical Center",
    "Research Institute for Tropical Medicine",
    "San Lazaro Hospital",
    "Sta. Ana Hospital",
    "Valenzuela City Health Office",
    "Baguio General Hospital and Medical Center",
    "Luis Hora Memorial Regional Hospital",
    "Ilocos Training and Regional Medical Center",
    "Mariano Marcos Memorial Hospital and Medical Center",
    "Pangasinan Provincial Hospital",
    "Region I Medical Center",
    "Cagayan Valley Medical Center",
    "Southern Isabela Medical Center",
    "Bataan General Hospital And Medical Center",
    "Jose B. Lingad Memorial Regional Hospital",
    "President Ramon Magsaysay Memorial Hospital",
    "Tarlac Provincial Hospital",
    "Oriental Mindoro Provincial Hospital",
    "Corazon Locsin Montelibano Memorial Regional Hospital",
    "Dr Rafael S. Tombokon Memorial Provincial Hospital",
    "Cebu TB Reference Laboratory",
    "Gov. Celestino Gallares Memorial Hospital",
    "Vicente Sotto Memorial Medical Center",
    "Eastern Visayas Regional Medical Center",
    "Northern Mindanao Medical Center",
    "Davao Regional Medical Center",
    "Southern Philippines Medical Center",
    "Cotabato Regional and Medical Center",
    "Adela Serra Ty Memorial Medical Center",
    "D.O. Plaza Memorial Hospital",
    "Culion Sanitarium and General Hospital",
    "Dr. Jose Fabella Memorial Hospital",
    "Quirino Memorial Medical Center",
    "Benguet General Hospital",
    "Dr. Paulino J. Garcia Memorial Research and Medical Center",
    "Amai Pakpak Medical Center",
    "East Avenue Medical Center",
    "Jose R. Reyes Memorial Medical Center",
    "Region II Trauma and Medical Center",
    "Southern Tagalog Regional Hospital Molecular Laboratory",
    "Bicol Regional Training and Teaching Hospital",
    "Dr. Jose Rizal Memorial Hospital",
    "Rizal Medical Center",
    "Gabriela Silang General Hospital (Ilocos Sur Provincial Hospital)",
    "Caraga Regional Hospital",
    "Siargao District Hospital"
  )
)


